#!/bin/bash
gmp="gmp-6.1.2"
url="https://github.com/cthbst/2018_Algo/raw/master/HW0/gmp-6.1.2.tar.gz"

if [ ! -f $gmp.tar.gz ] ; then
	curl -L $url/$gmp.tar.gz | tar -xzf -
else
	tar -xzf $gmp.tar.gz
fi

cd $gmp
./configure --disable-shared --enable-cxx
make --jobs=4 CFLAGS="-O3 -pipe"
cd ..
echo "GMP installed successfully."

