#!/bin/bash
url="https://github.com/cthbst/2018_Algo/raw/master/HW0"

# Download m4
m4="m4-1.4"
if [ ! -f $m4.tar.gz ] ; then
	# curl -L $url/$m4.tar.gz | tar -xzf -
	wget $url/$m4.tar.gz
	tar -xzf $m4.tar.gz
else
	tar -xzf $m4.tar.gz
fi

# Install m4
cd $m4
./configure --disable-shared
make --jobs=4 CFLAGS="-O3 -pipe"
PATH=$(pwd)/src/:$PATH
cd ..
echo "m4 installed successfully."


# Download GMP
gmp="gmp-6.1.2"
if [ ! -f $gmp.tar.gz ] ; then
	# curl -L $url/$gmp.tar.gz | tar -xzf -
	wget $url/$gmp.tar.gz
	tar -xzf $gmp.tar.gz
else
	tar -xzf $gmp.tar.gz
fi

# Install GMP
cd $gmp
./configure --disable-shared --enable-cxx
make --jobs=4 CFLAGS="-O3 -pipe"
cd ..
echo "GMP installed successfully."

rm m4* $gmp.tar.gz -rf

# Download compile
if [ ! -f compile ] ; then
	#curl -L $url/compile -o compile
	wget $url/compile
	chmod +x compile
fi
