#!/bin/bash
url="https://github.com/cthbst/2018_Algo/raw/master/HW0"
m4="m4-1.4"
gmp="gmp-6.1.2"

# Download m4
if [ ! -f $m4.tar.gz ] ; then
	echo "Downloading m4" 1>&2
	# curl -L $url/$m4.tar.gz | tar -xzf -
	wget --quiet $url/$m4.tar.gz && echo "m4 downloaded" 1>&2
fi

# Unzip m4
echo "Unzipping m4" 1>&2
tar -xzf $m4.tar.gz && echo "m4 unzipped" 1>&2

# Install m4
echo "Installing m4"
cd $m4
./configure --quiet --disable-shared --prefix=$(pwd)
make --quiet --jobs=8 CFLAGS="-O3 -pipe -w -static" && echo "m4 installed" 1>&2
make install
M4=$(pwd)/bin/m4
$M4 --version 1>&2 || exit 1
cd ..

# Download GMP
if [ ! -f $gmp.tar.gz ] ; then
	echo "Downloading gmp" 1>&2
	# curl -L $url/$gmp.tar.gz | tar -xzf -
	wget --quiet $url/$gmp.tar.gz && echo "gmp downloaded" 1>&2 
fi

# Unzip gmp
echo "Unzipping gmp" 1>&2
tar -xzf $gmp.tar.gz && echo "gmp unzipped" 1>&2

# Install GMP
echo "Installing gmp" 1>&2
cd $gmp
mkdir tmp
./configure --quiet --disable-shared --enable-cxx TMPDIR=tmp M4=$M4
make --quiet --jobs=8 CFLAGS="-O3 -pipe" && echo "gmp installed" 1>&2
rm -rf tmp
cd ..
rm -rf *.tar.gz
rm -rf $m4/

# Download compile
if [ ! -f compile ] ; then
	echo "Downloading compile" 1>&2
	#curl -L $url/compile -o compile
	wget --quiet $url/compile && echo "compile downloaded" 1>&2
	chmod +x compile
fi
